Fix a test failure caused by an internal docutils `open()` call
docutils 0.22 introduced an RST stylesheet feature
that must be able to open files during RST-to-HTML rendering.

The original design of the `test_cli_explicit_format` test
patched `pathlib.Path.open()` so it would always return the
same open file instance...which was always closed on first use.
This caused a failure when docutils tried to open `minimal.css`:

```
ValueError: I/O operation on closed file.
```

This change introduces a temporary input file to read from,
rather than attempting to mock `pathlib.Path.open()`.